version: '3'
services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3006:3006'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    restart: always
    build: ./api
    ports:
      - '5050:5050'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: kevinjia
      MONGO_INITDB_ROOT_PASSWORD: 19840619
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kevinjia
      ME_CONFIG_MONGODB_ADMINPASSWORD: 19840619
      ME_CONFIG_MONGODB_URL: mongodb://kevinjia:19840619@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongodb_data: